/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.akiraly.tdd

import io.kotest.assertions.asClue
import io.kotest.core.spec.style.AnnotationSpec
import io.kotest.matchers.shouldNotBe
import net.akiraly.tdd.AppTest.ParseState

class AppTest : AnnotationSpec() {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = App()
        "app should have a greeting".asClue {
            classUnderTest.greeting shouldNotBe null
        }
    }

    fun interface ParseState: (Char) -> ParseState

    class StringState : ParseState {
        override fun invoke(char: Char): ParseState {
            TODO("Not yet implemented")
        }

        val escaped = ParseState { char -> this@StringState }

        val unescaped = ParseState { char -> this@StringState }
    }

    fun foo() {

    }
}